# all vars (not all apply to all operating systems)

# homebrew casks to use (Darwin-only)
brew_casks:
  - sublime-text3

# homebrew packages to install (Darwin-only)
brew_pkgs:
  - coreutils
  - zsh
  - ssh-copy-id
  - tree
  - wget
  - openssl
  - libyaml
  - tmux
  - git
  - vim

# homebrew taps to use (Darwin-only)
brew_taps:
  - caskroom/versions

# gitconfig: user.name
git_config_name: Daniel Schmidt

# gitconfig: core.editor
git_config_editor: vim

# gitconfig: user.email
git_config_email: danschmidt5189@berkeley.edu

# URL of the oh-my-zsh install script. Point at fork!
oh_my_zsh_install_url: https://raw.githubusercontent.com/danschmidt5189/oh-my-zsh/master/tools/install.sh

# oh-my-zsh plugins to install. Override per-operating system as necessary.
oh_my_zsh_plugins: gitfast nyan vi-mode

# Sublime Text's configuration directory
sublime_text_root: "{{ansible_env.HOME}}/Library/Application Support/Sublime Text 3"
